# Generated by Django 3.2.5 on 2021-09-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210905_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correct_answer_count',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='wrong_count',
            new_name='wrong_answer_count',
        ),
    ]
